#Add here the messages you want to hide from your console and logs.
#Each line represents a new message.
#NOTE! You don't need to add the full message!
#The plugin will hide all messages that contain the text added below.
# EXAMPLE:
#
# Messages-To-Hide-Filter:
# - 'WARNING: unlocalizedName'
#
# To use regex, add "@" prefix in that line
#
# All messages that will appear in the server console that contain these words 'WARNING: unlocalizedName' will be hidden and they will not appear on logs or console.
# If you have large errors you don'tt have to type the full error. But the more words you add the more accurate will be and will not hide other messages that may contain the words added in the filter.

Messages-To-Hide-Filter:
  - 'WARNING: unlocalizedName'
  - 'look up profile properties for'
  - 'InitialHandler - NativeIoException: readAddress(..) failed: Connection reset by peer'